### ISSUE TITLE
Option to add different apidocs to config

### ISSUE THREAD

**Issue by 7sharp9** [sharvil/api-docs#14]
To add rust I had to modify library.js and add 'rust'

Perhaps scraping the current file extension/type would yield only relevant results?

**Comment by danielbrodin** [comment]
There is a config to add languages, for example rust. When the package is installed it has to create a setting for each language though so you might have to restart atom for them to show up.

**Comment by aviflax** [comment]
Restarting did it for me! Thanks!

**Comment by Alphanumerix** [comment]
How about some notification to restart atom? Is this possible to display such information after plugin is installed?
