### ISSUE TITLE
Issue with Atom Material

### ISSUE THREAD

**Issue by Unforgiven-wanda** [sharvil/api-docs#15]
Hi,
using Atom Material theme, there is an issue with the color of the font. It is grey on white making it hardly readable. Is there some way to tweak the font color?

Here's a screen
![untitled](https://cloud.githubusercontent.com/assets/4499783/10818449/eef43cca-7e41-11e5-9a71-679605f4134e.png)

*learning freakin' Meteor*

Thank you.

**Comment by pcanterini** [comment]
Same issue here with most of the dark themes I use.
I might attempt a PR for font color settings later this week, time allowing.

**Comment by sharvil** [comment]
You can choose between a light and dark color scheme from the api-docs settings. Let me know if that doesn't help.
