### ISSUE TITLE
Closing the browser on a split pane closes all files on pane

### ISSUE THREAD

**Issue by YourPsychiatrist** [sharvil/api-docs#17]
Example:
I have a css file on the left and a js file on the right pane. Now when i try to open the API documentation browser for document.documentElement from the js file it opens the browser as expected. But when i close that browser tab, it closes the js file with it and all other files on that split pane, only css file (and other files on left pane) are opened! Am i missing something?

**Comment by danielbrodin** [comment]
This was fixed with https://github.com/sharvil/api-docs/pull/13, but there haven't been a release with it for some reason.

**Comment by dirk-thomas** [comment]
Version 0.0.4 has been released since then (on February 7th).
