### ISSUE TITLE
Doesn't find the right spot

### ISSUE THREAD

**Issue by kgrossjo** [sharvil/api-docs#18]
I installed api-docs 0.0.3 and I enabled Python.  I disabled the keybindings.  I used Command-P to invoke the API Docs Search function, and I entered "re.search".  This suggested `re.search()` as one of the options, which is good.  I selected it.  This opens the page for the module `re` in the browser, but it doesn't scroll to the place where `re.search()` is documented.

I think it should scroll to the right spot.

**Comment by HunterNL** [comment]
Similar issue with the Meteor docs, it just opens the very top of the Meteor docs page. Doesn't matter if I use the keybind or command palette.

Running version 0.0.5 on Atom 1.8.0

**Comment by dirk-thomas** [comment]
Many language docs have one page per slug. In these cases the slug is actually part of a bigger page and referenced in the url using a hash. Please consider trying the code from PR #34 which adds the feature to scroll to the passed id if it is found in the page.

**Comment by nnals** [comment]
hello,
i'm running 0.0.6 which should include #34 but e.g. searching for `fs.writeFileSync` does not jump to the right anchor. is this a known issue?
thank you!
