### ISSUE TITLE
Unhandled promise rejection errors in Console

### ISSUE THREAD

**Issue by batjko** [sharvil/api-docs#2]
Hi there,

I'm finding these errors in the console whenever the package gets activated:
![image](https://cloud.githubusercontent.com/assets/7287076/8184391/12aad938-1436-11e5-9d66-1fd2215c0f43.png)

The key binding has clearly been registered, however, even though it is being overridden by the binding from find-and-replace:

![image](https://cloud.githubusercontent.com/assets/7287076/8184462/7a9137fe-1436-11e5-9431-f8f2f04b781d.png)

Win7, 64bit, Atom v209.

Anything else I can provide to help analyze the issue?

**Comment by hindsholm** [comment]
I have the same problem, although here it is a timeout error.
![api-docs](https://cloud.githubusercontent.com/assets/1001136/8429823/9bc56454-1f2b-11e5-9137-5ee6033a36b6.png)

The error disappears when I uninstall api-docs.

Win7, 64bit, Atom 1.0.0.

PS: I am using api-docs on my Linux laptop, and it is great, so I hope you can fix this error.

**Comment by batjko** [comment]
@hindsholm Yours seems to be a connection error actually, trying to reach the IP mentioned in that screenshot. Are you behind a proxy or firewall?

**Comment by hindsholm** [comment]
Yes, it does indeed look like a connection error, and I am behind a coporate firewall with a proxy.
I posted it here anyway, because I have not seen other connection errors in Atom - although I have just installed it today, so it might be a bit early to say. I have installed a few other packages without errors.

**Comment by batjko** [comment]
Do you have issues installing or using any other packages?
In which case your issue might be more closely related to https://github.com/atom/apm/issues/322.

**Comment by hindsholm** [comment]
No, like I said, I have installed other packages.

This is my apm setup:
```
c:\Users\mohi\AppData\Local\atom\bin>apm config ls
; cli configs
globalconfig = "C:\\Users\\mohi\\.atom\\.apm\\.apmrc"
user-agent = "npm/2.5.1 node/v0.10.35 win32 ia32"
userconfig = "C:\\Users\\mohi\\.atom\\.apmrc"

; userconfig C:\Users\mohi\.atom\.apmrc
http-proxy = "http://webproxy:8080"
https-proxy = "http://webproxy:8080/"
proxy = "http://webproxy:8080/"
strict-ssl = false

; globalconfig C:\Users\mohi\.atom\.apm\.apmrc
cache = "C:\\Users\\mohi\\.atom\\.apm"

; node bin location = c:\Users\mohi\AppData\Local\atom\app-1.0.0\resources\app\apm\bin\node.exe
; cwd = c:\Users\mohi\AppData\Local\atom\bin
; HOME = C:\Users\mohi
; 'npm config ls -l' to show all defaults.
```

Inspired by https://github.com/atom/apm/issues/322 I tried installing a few packages from the command line:
```
c:\Users\mohi\AppData\Local\atom\bin>apm install api-docs
Installing api-docs to C:\Users\mohi\.atom\packages done
c:\Users\mohi\AppData\Local\atom\bin>apm install minimap
Installing minimap to C:\Users\mohi\.atom\packages done
```

Installation goes fine, but on startup, api-docs still causes the unhandled promise rejection.

**Comment by sharvil** [comment]
@batjko, can you take a look at the files in C:\Users\tthpmx\.atom\packages\api-docs\data and see if there are any files that aren't valid JSON (other than style-light.css)? Alternatively, you can send those files to my email address (sharvil.nanavati@gmail.com).

@hindsholm, do you have a docs.json file in C:\Users\mohi\.atom\packages\api-docs\data?

Thanks for reporting these errors!

**Comment by batjko** [comment]
I have just re-installed the package and this error doesn't seem to occur anymore.

**Comment by sharvil** [comment]
@hindsholm, I think the referenced commit should fix the issue you're running into with your Windows machine. Please submit another issue if you're still having trouble after upgrading to api-docs 0.0.2.

**Comment by hindsholm** [comment]
Thank you for your reply. I am on vacation right now (luckily without Windows) but I will test the fix when I get back.
