### ISSUE TITLE
"No matches found" for all

### ISSUE THREAD

**Issue by gsfarm** [sharvil/api-docs#22]
The plugin not working. Not give results for any search.

**Comment by herophuong** [comment]
Getting this error in console:

    /Users/[...]/.atom/packages/api-docs/src/docset.js:44 
    Uncaught (in promise) SyntaxError: Unexpected token <(…)

**Comment by gsfarm** [comment]
I not looked console output. Indeed, the error specified **herophuong**. The plugin can't parse JSON. Instead of JSON comes `401 Authorization Required`.

**Comment by sharvil** [comment]
I'll be pushing a new version with the fix shortly.
