### ISSUE TITLE
will it add php support?

### ISSUE THREAD

**Issue by MagiCarbon** [sharvil/api-docs#28]
no php support in current version. plz add it, thanks.

**Comment by rsweetland** [comment]
php support works for me, although it has to be manually enabled within in the package settings.

Popular php frameworks are also there (Laravel, Symfony, etc) 👍

**Comment by dirk-thomas** [comment]
This package supports all languages available on devdocs.io which already has support for PHP. You might need to enable PHP in the settings page of this package though.

**Comment by dirk-thomas** [comment]
I have added a note to the README page to clarify that you need to enable languages in the settings: #32
