### ISSUE TITLE
keeps loading for python2 and python3.5.

### ISSUE THREAD

**Issue by jshn** [sharvil/api-docs#29]
Hi!

This is really an outstanding plugin and I like it a lot so far! :)
However, I run into issues when trying to use Python2.7 och Python3.5.
When I try to search for a word the window openes, but just keeps loading and nothing more happens.

When I debug your code on line: 36 in doc_view.js, it seams like the path is a bit strange and is set to ex.: "3.5~/library/import". This might not be the problem, but if I do the same search for html which works, the path is set to: "element/a" which seams a bit cleaner with no path-prefix.

I really would love this to work also for Python!

Many thanks!

**Comment by fwoelm** [comment]
Have the same issue when looking up Rails or Ruby commands. It is able to identify the command correctly (see image), but then the api pane is stuck loading forever. Also, as you can see on the screenshot, the tiny icons that indicate the language do not show up , which probably is a hint that some paths are wrong.

PS: HTML, CSS, and JS documentation work wonderfully.

![rails_issue](https://cloud.githubusercontent.com/assets/7606194/15807175/1194d718-2b57-11e6-993e-dcd1b7688537.png)

**Comment by ostapiuk** [comment]
I'm having the exact same issue with Perl - missing icon and page never loads.  Other docs I've tried work fine (CSS, Less, HTML).

**Comment by dirk-thomas** [comment]
#30 should fix the icon problem and #31 should fix opening the docs. Both issues were related to having a tilde in the slug name of the language.
