### ISSUE TITLE
[Feature Requests] option to browse documentation independent of code 

### ISSUE THREAD

**Issue by AmeBel** [sharvil/api-docs#3]
First thanks for starting this.

It would be great to be able to browse the  the documentation independent of code. Somewhat similar to https://devdocs.io/offline.

**Comment by mayowa** [comment]
You could also show an input box and allow direct searching (if that would be easier)

**Comment by danielbrodin** [comment]
This actually already works, it's just that the command makes it sound like it only takes what is under the cursor. So just run the command, then search for whatever you want

**Comment by AmeBel** [comment]
ok thanks
