### ISSUE TITLE
Code fragments have dark background on Atom default Mac theme

### ISSUE THREAD

**Issue by dnachev** [sharvil/api-docs#5]
All code fragments (&lt;code&gt; elements) have dark background on the Atom default theme on Mac (it may be the default theme for the other OS as well).

![main_less_-__users_dnachev_projects_autocomplete-plus_-_atom](https://cloud.githubusercontent.com/assets/816847/8395463/b2d802a2-1d26-11e5-9ed3-bab94180e518.png)

**Comment by sharvil** [comment]
This happens because the doc view isn't running inside a shadow root. The current theme's CSS is leaking into the doc view and screwing up its styles. The proper fix to this issue is blocked on https://github.com/atom/atom/issues/5388.
