### ISSUE TITLE
The api docs are not showing in atom editor

### ISSUE THREAD

**Issue by astrolemonade** [sharvil/api-docs#50]
If I press the ctrl-d and it shows the type box and search some basic things of the installed docs nothing shows

**Comment by tw00** [comment]
Seems to have problem while fetching data from devdocs.io. (Maybe HTTP.get not following redirects?)
I downloaded the required docs.json manually and it seems to work now.
You can use the following command:

```bash
curl -L https://devdocs.io/docs.json > ~/.atom/packages/api-docs/data/docs.json
```

Cheers

**Comment by astrolemonade** [comment]
I am using windows

În mar., 29 ian. 2019, 02:43 Thomas <notifications@github.com a scris:

**Comment by v-ko** [comment]
Had the same problem. The manual download @tw00 proposed solved the issue. Nevertheless I wanted to confirm that the bug is present, and there's no warning info that there are connection issues.
