### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by RomFouq** [sharvil/api-docs#7]
Your package is really useful! It makes searches on devdocs much faster.  
The menu is also beautiful but the result page should have a dark theme, for example, the one of devdocs, or even better, it could adapt itself to the current user UI theme.

**Comment by sharvil** [comment]
Thanks for the suggestion! You'll be able to select between a light / dark theme in the next release.

**Comment by RomFouq** [comment]
I just had the update, that's really better. Thanks a lot! :tada:
